#!/bin/bash

for run in {1..30}
do
    echo "Iteration: $run"

    python train.py \
            --dataset cora \
            --checkpt_file pre_trained/cora/cora_mod.ckpt \
            --train_size 5 \
            --validation_size 500 \
            --dropout 0.6 \
            --seed $run \
	    >> gndnets_mlp_cora_5.txt
done

python calculate_average_accuracy.py \
        --file_name gndnets_mlp_cora_5.txt \
