#!/bin/bash

for run in {1..30}
do
    echo "Iteration: $run"

    python train.py \
            --dataset amazon_c \
            --checkpt_file pre_trained/amazon_p/amazon_c_mod.ckpt \
            --train_size 3 \
            --validation_size 500 \
            --dropout 0.6 \
            --seed $run \
	    >> gndc_mlp_amazonc_3.txt
done

python calculate_average_accuracy.py \
        --file_name gndc_mlp_amazonc_3.txt \
